#!/bin/sh
ln -s "$PWD/.emacs" "$HOME"
ln -s "$PWD/.gitconfig" "$HOME"
ln -s "$PWD/.screenrc" "$HOME"
ln -s "$PWD/.tmux.conf" "$HOME"
ln -s "$PWD/.vim" "$HOME"
ln -s "$PWD/.vimrc" "$HOME"
ln -s "$PWD/.zshenv" "$HOME"
ln -s "$PWD/.subversion" "$HOME"
ln -s "$PWD/.Xresources" "$HOME"
