
[window]
option_as_alt = "OnlyLeft"
dimensions = { columns = 110, lines = 40 }

[scrolling]
history = 20000

[selection]
save_to_clipboard = true

[font]
normal = { family = "Iosevka Term", style = "Regular" }
size = 16

[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
]
